// eslint-disable-next-line no-unused-vars
import React, { useEffect, useRef, useState } from "react";

const Search = () => {
  const [Querry, setQuerry] = useState("");
  const [Suggestions, setSuggestions] = useState([]);
  const SearchInput = useRef(null);
  const allSuggestion = [
    "Smartphone",
    "Laptop",
    "Tablet",
    "Smartwatch",
    "Headphones",
    "Wireless Earbuds",
    "Bluetooth Speaker",
    "Portable Charger",
    "USB-C Cable",
    "Wireless Mouse",
    "Gaming Keyboard",
    "Monitor",
    "External Hard Drive",
    "Smart TV",
    "VR Headset",
    "Digital Camera",
    "Drone",
    "Fitness Tracker",
    "Smart Light Bulb",
    "Smart Thermostat",
    "Home Security Camera",
    "Electric Toothbrush",
    "Hair Dryer",
    "Air Purifier",
    "Coffee Maker",
    "Blender",
    "Microwave Oven",
    "Air Fryer",
    "Electric Kettle",
    "Vacuum Cleaner",
    "Dishwasher",
    "Washing Machine",
    "Refrigerator",
    "Oven",
    "Toaster",
    "Mixer Grinder",
    "Rice Cooker",
    "Induction Cooktop",
    "Water Purifier",
    "Water Heater",
    "Electric Iron",
    "Electric Shaver",
    "Hair Straightener",
    "Curling Iron",
    "Smart Door Lock",
    "Smart Plug",
    "Smart Security System",
    "Smart Doorbell",
    "Pet Tracker",
    "Baby Monitor",
    "Electric Scooter",
    "Electric Bike",
    "Car Dash Cam",
    "GPS Navigator",
    "Portable Generator",
    "Camping Tent",
    "Sleeping Bag",
    "Portable Cooler",
    "Action Camera",
    "Instant Camera",
    "Photo Printer",
    "Wireless Router",
    "Mesh Wi-Fi System",
    "Network Switch",
    "Smart Speaker",
    "Soundbar",
    "Streaming Device",
    "Media Player",
    "Portable Projector",
    "Electric Skillet",
    "Pressure Cooker",
    "Slow Cooker",
    "Popcorn Maker",
    "Juicer",
    "Food Processor",
    "Hand Mixer",
    "Stand Mixer",
    "Bread Maker",
    "Ice Cream Maker",
    "Pizza Oven",
    "Waffle Maker",
    "Deep Fryer",
    "Sandwich Maker",
    "Electric Grill",
    "Portable BBQ",
    "Charcoal Grill",
    "Gas Grill",
    "Smoker",
    "Food Dehydrator",
    "Food Steamer",
    "Pasta Maker",
    "Vacuum Sealer",
    "Hand Blender",
    "Salad Spinner",
    "Cheese Grater",
    "Cutting Board",
    "Knife Set",
    "Cookware Set",
    "Non-Stick Pan",
    "Pressure Washer",
    "Lawn Mower",
    "Leaf Blower",
    "Hedge Trimmer",
    "Chainsaw",
    "Garden Hose",
    "Garden Shears",
    "Watering Can",
    "Pruning Shears",
    "Plant Pots",
    "Compost Bin",
    "Greenhouse",
    "Garden Cart",
    "Wheelbarrow",
    "Rake",
    "Shovel",
    "Garden Fork",
    "Ladder",
    "Tool Set",
    "Power Drill",
    "Hammer",
    "Screwdriver Set",
    "Wrench Set",
    "Pliers Set",
    "Measuring Tape",
    "Level",
    "Stud Finder",
    "Utility Knife",
    "Flashlight",
    "Batteries",
    "Extension Cord",
    "Surge Protector",
    "First Aid Kit",
    "Fire Extinguisher",
    "Smoke Detector",
    "Carbon Monoxide Detector",
    "Home Alarm System",
    "Personal Safety Alarm",
    "Pepper Spray",
    "Stun Gun",
    "Door Security Bar",
    "Window Locks",
    "Safe",
    "Document Shredder",
    "Office Chair",
    "Standing Desk",
    "Desk Lamp",
    "Monitor Stand",
    "Laptop Stand",
    "Keyboard Tray",
    "Ergonomic Mouse",
    "Footrest",
    "Whiteboard",
    "Corkboard",
    "File Organizer",
    "Paper Shredder",
    "Printer",
    "Scanner",
    "Laminator",
    "Label Maker",
    "Post-it Notes",
    "Highlighters",
    "Pens",
    "Pencils",
    "Markers",
    "Stapler",
    "Hole Puncher",
    "Binder Clips",
    "Paper Clips",
    "Tape Dispenser",
    "Glue Stick",
    "Scissors",
    "Ruler",
    "Calculator",
    "Envelopes",
    "Manila Folders",
    "Binders",
    "Notebooks",
    "Legal Pads",
    "Planner",
    "Desk Organizer",
    "Magazine Rack",
    "Trash Can",
    "Recycling Bin",
    "Water Bottle",
    "Lunch Box",
    "Thermos",
    "Backpack",
    "Messenger Bag",
    "Laptop Bag",
    "Tablet Sleeve",
    "Phone Case",
    "Screen Protector",
    "Wallet",
    "Keychain",
    "Sunglasses",
    "Hat",
    "Beanie",
    "Scarf",
    "Gloves",
    "Umbrella",
    "Raincoat",
    "Jacket",
    "Sweater",
    "Hoodie",
    "T-shirt",
    "Jeans",
    "Pants",
    "Shorts",
    "Skirt",
    "Dress",
    "Blouse",
    "Shirt",
    "Suit",
    "Tie",
    "Belt",
    "Socks",
    "Shoes",
    "Boots",
    "Sandals",
    "Slippers",
    "Sneakers",
    "Watch",
    "Bracelet",
    "Necklace",
    "Earrings",
    "Ring",
    "Handbag",
    "Purse",
    "Duffel Bag",
    "Suitcase",
    "Luggage Set",
    "Travel Pillow",
    "Travel Adapter",
    "Passport Holder",
    "Luggage Tags",
    "Sleeping Mask",
    "Earplugs",
    "Compression Socks",
    "Camera Bag",
    "Tripod",
    "Lens",
    "Camera Strap",
    "Memory Card",
    "Card Reader",
    "Portable Hard Drive",
    "USB Flash Drive",
    "Power Bank",
    "Car Charger",
    "Wireless Charger",
    "Docking Station",
    "HDMI Cable",
    "Ethernet Cable",
    "Audio Cable",
    "Video Cable",
    "Adapter",
    "Converter",
    "Splitters",
    "Switch",
    "Router",
    "Modem",
    "Access Point",
    "Range Extender",
    "Powerline Adapter",
    "Network Cable Tester",
    "Cable Management Kit",
    "Label Printer",
    "Barcode Scanner",
    "Receipt Printer",
    "Cash Register",
    "POS Terminal",
    "Credit Card Reader",
    "Handheld Scanner",
    "Price Gun",
    "Security Tags",
    "Anti-theft System",
    "Shelving Unit",
    "Display Stand",
    "Mannequin",
    "Clothing Rack",
    "Hangers",
    "Garment Bag",
    "Sewing Machine",
    "Thread",
    "Fabric",
    "Buttons",
    "Zippers",
    "Needles",
    "Scissors",
    "Pattern",
    "Dress Form",
    "Ironing Board",
    "Iron",
    "Steamer",
    "Clothesline",
    "Drying Rack",
    "Laundry Basket",
    "Clothespins",
    "Lint Roller",
    "Fabric Softener",
    "Detergent",
    "Bleach",
    "Stain Remover",
    "Fabric Freshener",
    "Washing Machine Cleaner",
    "Dryer Sheets",
    "Dryer Balls",
    "Sewing Kit",
    "First Aid Kit",
    "Survival Kit",
    "Emergency Blanket",
    "Fire Starter",
    "Water Purification Tablets",
    "Flashlight",
    "Multi-tool",
    "Compass",
    "Map",
    "Whistle",
    "Signal Mirror",
    "Rope",
    "Tarp",
    "Tent",
    "Sleeping Bag",
    "Camping Stove",
    "Propane Tank",
    "Cookware Set",
    "Utensils",
    "Plates",
    "Cups",
    "Cutlery",
    "Cooler",
    "Ice Packs",
    "Camping Chair",
    "Camping Table",
    "Lantern",
    "Headlamp",
    "Insect Repellent",
    "Sunscreen",
    "Sunglasses",
    "Hat",
    "Gloves",
    "Jacket",
    "Raincoat",
    "Backpack",
    "Hiking Boots",
    "Walking Stick",
    "Binoculars",
    "Camera",
    "Tripod",
    "Lens",
    "Memory Card",
    "Battery Charger",
    "Power Bank",
    "Portable Solar Panel",
    "Satellite Phone",
    "Walkie Talkie",
    "Personal Locator Beacon",
    "GPS Device",
    "Portable Toilet",
    "Toilet Paper",
    "Hand Sanitizer",
    "Wet Wipes",
    "Soap",
    "Shampoo",
    "Conditioner",
    "Toothbrush",
    "Toothpaste",
    "Floss",
    "Mouthwash",
    "Razor",
    "Shaving Cream",
    "Aftershave",
    "Deodorant",
    "Perfume",
    "Cologne",
    "Nail Clipper",
    "Nail File",
    "Tweezers",
    "Mirror",
    "Makeup",
    "Lip Balm",
    "Sunscreen",
    "Moisturizer",
    "Facial Cleanser",
    "Toner",
    "Serum",
    "Eye Cream",
    "Face Mask",
    "Hairbrush",
    "Comb",
    "Hair Ties",
    "Hair Clips",
    "Hair Dryer",
    "Hair Straightener",
    "Curling Iron",
    "Hair Spray",
    "Hair Gel",
    "Hair Wax",
    "Hair Oil",
    "Shampoo",
    "Conditioner",
    "Hair Mask",
    "Leave-in Conditioner",
    "Hair Serum",
    "Heat Protectant",
    "Detangler",
    "Scalp Treatment",
    "Anti-dandruff Shampoo",
    "Dry Shampoo",
    "Volumizing Mousse",
    "Texturizing Spray",
    "Hairspray",
    "Hair Pomade",
    "Beard Oil",
    "Beard Balm",
    "Beard Comb",
    "Beard Trimmer",
    "Mustache Wax",
    "Shaving Soap",
    "Shaving Brush",
    "Straight Razor",
    "Safety Razor",
    "Razor Blades",
    "Aftershave Balm",
    "Shaving Cream",
    "Shaving Gel",
    "Shaving Oil",
    "Exfoliating Scrub",
    "Face Wash",
    "Face Scrub",
    "Face Toner",
    "Face Serum",
    "Face Oil",
    "Face Mask",
    "Eye Cream",
    "Lip Balm",
    "Hand Cream",
    "Body Lotion",
    "Body Wash",
    "Body Scrub",
    "Body Butter",
    "Body Oil",
    "Bath Salts",
    "Bubble Bath",
    "Bath Bomb",
    "Foot Cream",
    "Foot Scrub",
    "Foot Soak",
    "Nail Polish",
    "Nail Polish Remover",
    "Nail Clipper",
    "Nail File",
    "Cuticle Pusher",
    "Cuticle Oil",
    "Nail Buffer",
    "Nail Brush",
    "Nail Strengthener",
    "Nail Hardener",
    "Base Coat",
    "Top Coat",
    "Quick Dry Spray",
    "Nail Stickers",
    "Nail Art Kit",
    "Gel Nail Polish",
    "Acrylic Nails",
    "Nail Glue",
    "Nail Tips",
    "Nail Forms",
    "Nail Drill",
    "Nail Lamp",
    "Manicure Set",
    "Pedicure Set",
    "Makeup Brushes",
    "Makeup Sponge",
    "Foundation",
    "Concealer",
    "Setting Powder",
    "Blush",
    "Bronzer",
    "Highlighter",
    "Eyeshadow",
    "Eyeliner",
    "Mascara",
    "Eyebrow Pencil",
    "Eyebrow Gel",
    "Eyebrow Powder",
    "Lipstick",
    "Lip Gloss",
    "Lip Liner",
    "Lip Plumper",
    "Makeup Remover",
    "Cleansing Wipes",
    "Cleansing Oil",
    "Micellar Water",
    "Toner",
    "Serum",
    "Moisturizer",
    "Sunscreen",
    "Face Primer",
    "Setting Spray",
    "Makeup Bag",
    "Makeup Organizer",
    "Vanity Mirror",
    "Brush Cleaner",
    "Brush Holder",
    "Beauty Blender",
    "Makeup Sponge",
    "Contour Kit",
    "Highlighting Kit",
    "Eyeshadow Palette",
    "Brow Kit",
    "Lip Kit",
    "Nail Kit",
    "Hair Kit",
    "Skincare Kit",
    "Fragrance Set",
    "Gift Set",
    "Beauty Subscription Box",
    "Perfume",
    "Cologne",
    "Body Mist",
    "Body Spray",
    "Body Lotion",
    "Body Cream",
    "Body Oil",
    "Body Scrub",
    "Body Butter",
    "Body Wash",
    "Bath Oil",
    "Bath Salts",
    "Bubble Bath",
    "Bath Bomb",
    "Shower Gel",
    "Hand Wash",
    "Hand Cream",
    "Foot Cream",
    "Foot Scrub",
    "Foot Mask",
    "Foot Peel",
    "Foot Soak",
    "Exfoliating Scrub",
    "Exfoliating Gloves",
    "Exfoliating Mitt",
    "Loofah",
    "Shower Pouf",
    "Shower Cap",
    "Bath Pillow",
    "Bath Mat",
    "Bath Towel",
    "Hand Towel",
    "Face Towel",
    "Washcloth",
    "Robe",
    "Slippers",
    "Eye Mask",
    "Ear Plugs",
    "Satin Pillowcase",
    "Satin Sleep Mask",
    "Satin Scrunchie",
    "Satin Hair Wrap",
    "Satin Bonnet",
    "Silk Pillowcase",
    "Silk Eye Mask",
    "Silk Scrunchie",
    "Silk Hair Wrap",
    "Silk Bonnet",
    "Cotton Pillowcase",
    "Cotton Sheets",
    "Cotton Duvet Cover",
    "Cotton Blanket",
    "Cotton Throw",
    "Cotton Towels",
    "Cotton Robe",
    "Cotton Slippers",
    "Cotton Pajamas",
    "Linen Pillowcase",
    "Linen Sheets",
    "Linen Duvet Cover",
    "Linen Blanket",
    "Linen Throw",
    "Linen Towels",
    "Linen Robe",
    "Linen Slippers",
    "Linen Pajamas",
  ];
  const SuggestionStyle = useRef(null)

  useEffect(() => {
    if (Querry == " ") {
      setSuggestions([]);
    } else {
      const FillterdSuggestion = allSuggestion.filter((item) =>
        item.toLowerCase().includes(Querry.toLowerCase())
      );
      setSuggestions(FillterdSuggestion);
     
    }
  }, [Querry]);
  return (
    <>
      <input
        ref={SearchInput}
        value={Querry}
        onChange={(e) => setQuerry(e.target.value)}
        className="border-black border-separate rounded-lg p-2 border-2 "
        type="text"
      />

      <ul 
       style={{display:"none"}}
       ref={SuggestionStyle}
      >
        {Suggestions.map((items, index) => (
          <li key={index}>{items}</li>
        ))};
      </ul>
    </>
  );
};

export default Search;
